# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - yarn --frozen-lockfile

cache:
  - node_modules
  - .eslintcache
  - "%LOCALAPPDATA%\\Yarn"

# Post-install test scripts.
test_script:
  # run tests
  - yarn test

# Don't actually build.
build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false